-- Tracks every PDF run through the admin-pdf-review.html scan pipeline, independent of
-- whether any questions from it ever get saved to `pyq`. Existing /admin/pdf-upload-history
-- infers history retroactively from pyq.source_pdf_filename, which can't represent a PDF
-- that was scanned but never saved, or one whose scan failed outright -- this table can.
create table if not exists processed_pdfs (
  id bigint generated by default as identity primary key,
  filename text not null,
  subject text,
  status text not null default 'pending' check (status in ('pending', 'processing', 'completed', 'failed')),
  questions_extracted integer not null default 0,
  error_message text,
  processed_by text,
  upload_date timestamptz not null default now(),
  processed_at timestamptz
);

create index if not exists idx_processed_pdfs_filename on processed_pdfs (filename);
create index if not exists idx_processed_pdfs_upload_date on processed_pdfs (upload_date desc);
