-- NCERT-style reference diagrams (Physics/Biology/Chemistry), uploaded via
-- admin-diagram-upload.html for later use in chat doubt-matching. This migration is
-- upload/storage schema only -- no matching logic depends on it yet.
create table if not exists public.diagrams (
  id bigint generated by default as identity primary key,
  subject text not null check (subject in ('Physics','Chemistry','Biology')),
  class integer,
  chapter text not null,
  name text not null,
  description text,
  image_url text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_diagrams_subject_chapter on public.diagrams (subject, chapter);

-- Same anon-read-only pattern as lock_down_pyq_rls.sql / create_mock_tests_tables.sql.
-- No INSERT/UPDATE/DELETE policy for anon/authenticated on purpose -- all writes go
-- through server.py's service-role key (ADMIN_HEADERS), same as pyq and mock_tests.
alter table public.diagrams enable row level security;
drop policy if exists "diagrams_public_select" on public.diagrams;
create policy "diagrams_public_select" on public.diagrams
  for select to anon, authenticated using (true);
