-- Official, admin-uploaded mock tests: a fixed, ordered 180-question set (Physics ->
-- Chemistry -> Biology) served to students instead of the random pyq draw used by
-- /mock-test-questions. mock_tests is both the tracking record (status/filename/timestamps,
-- like processed_pdfs) AND the strict FK parent of its questions -- one owns many via
-- cascade delete, unlike the loose processed_pdfs<->pyq filename-string relationship.
create table if not exists public.mock_tests (
  id bigint generated by default as identity primary key,
  title text not null,
  filename text,
  status text not null default 'pending' check (status in ('pending','processing','completed','failed')),
  is_published boolean not null default false,
  questions_extracted integer not null default 0,
  physics_count integer not null default 0,
  chemistry_count integer not null default 0,
  biology_count integer not null default 0,
  error_message text,
  created_at timestamptz not null default now(),
  published_at timestamptz
);

create table if not exists public.mock_test_questions (
  id bigint generated by default as identity primary key,
  mock_test_id bigint not null references public.mock_tests(id) on delete cascade,
  question_order integer not null,
  subject text not null check (subject in ('Physics','Chemistry','Biology')),
  chapter text,
  class integer,
  question text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_answer text not null default '',
  question_type text not null default 'mcq',
  year integer,
  has_diagram boolean not null default false,
  diagram_url text,
  option_a_diagram_url text,
  option_b_diagram_url text,
  option_c_diagram_url text,
  option_d_diagram_url text,
  unique (mock_test_id, question_order)
);
create index if not exists idx_mock_test_questions_order on public.mock_test_questions (mock_test_id, question_order);

-- Additive, nullable -- existing random-mode mock_results rows stay NULL, unaffected.
alter table public.mock_results add column if not exists mock_test_id bigint references public.mock_tests(id);
create index if not exists idx_mock_results_user_test on public.mock_results (user_id, mock_test_id);

-- Same anon-read-only pattern as lock_down_pyq_rls.sql. is_published gates visibility at
-- the DB layer itself, so a half-reviewed test can never leak even if an endpoint forgets
-- to filter -- important since mock_tests directly drives a student-facing picker, unlike
-- processed_pdfs which only ever fed an admin-only view.
alter table public.mock_tests enable row level security;
drop policy if exists "mock_tests_public_select" on public.mock_tests;
create policy "mock_tests_public_select" on public.mock_tests
  for select to anon, authenticated using (is_published = true);

alter table public.mock_test_questions enable row level security;
drop policy if exists "mock_test_questions_public_select" on public.mock_test_questions;
create policy "mock_test_questions_public_select" on public.mock_test_questions
  for select to anon, authenticated
  using (exists (select 1 from public.mock_tests t where t.id = mock_test_id and t.is_published = true));

-- No INSERT/UPDATE/DELETE policy for anon/authenticated on purpose -- all writes go
-- through server.py's service-role key, same as pyq.
