-- Queryable per-request provider/cost log for text-doubt generation (/chat, /solve -- DeepSeek
-- vs Qwen-Flash, see the peak-hour fallback in server.py) and image/PDF doubt generation (/chat
-- via Gemini). Upgrades the print-only "PROVIDER USAGE:" log line (still kept -- cheap, useful
-- for a quick Railway log check) to a real table, so the real per-provider cost/usage split can
-- be queried over time instead of assumed.
--
-- Purely additive: no existing table/column/row is touched. Safe to run once in the Supabase
-- SQL editor.

create table if not exists public.provider_usage_log (
  id bigint generated by default as identity primary key,
  user_id uuid,
  provider text not null check (provider in ('deepseek-v4-flash', 'qwen-flash', 'gemini-3.5-flash-lite')),
  peak_window boolean not null default false,
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  cost numeric(12, 8) not null default 0,
  endpoint text not null check (endpoint in ('/chat', '/solve')),
  created_at timestamptz not null default now()
);

-- Both indexes serve the obvious analytics queries: "cost/volume by provider over time" and
-- "everything in a given time range" (e.g. this month's spend).
create index if not exists idx_provider_usage_log_provider_created on public.provider_usage_log (provider, created_at);
create index if not exists idx_provider_usage_log_created on public.provider_usage_log (created_at);

-- Locked down entirely, same pattern as create_pyq_solution_cache.sql -- this is internal cost
-- telemetry, not user-facing content, so unlike pyq/mock_tests there's deliberately no public
-- SELECT policy either. The backend only ever reads/writes this table with the service-role
-- key (ADMIN_HEADERS in server.py), which bypasses RLS entirely.
alter table public.provider_usage_log enable row level security;
